### ISSUE TITLE
Using big-brain for target selection in an aiming system?

### ISSUE THREAD

**Issue by rosofo** [zkat/big-brain#107]
I'm figuring out how to model the following scenario:

- An automated turret/laser needs to figure out which entity to target 
- Targetable entities have a value
- The turret wants to maximise the total value of the enemies it's killing

It seems like it should be straightforward - the turret is the `Thinker`, the action it can take is `Aim { target: Entity }`, and there is a `Score` for each targetable entity, derived from its value/worth.

Questions:

- Is this the right way to think about utility ai/big brain? It feels like my approach is problematic because there's no type-level difference between different Aim instances, so there's no 'decision' being modelled
- If it can be done with big-brain, how can I ensure each targetable entity has a `Scorer`? How can I model actions which are too numerous to be known at compile time?

**Comment by rosofo** [comment]
Maybe this is just too granular, and big-brain is more designed for things where the Thinker has multiple priorities like `should I reload, aim or fire right now?`?

**Comment by zkat** [comment]
So, reframing this as a pathfinding example: You wouldn't use big-brain itself to calculate the _optimal path_. You would have an action, "FindPath", and _that_ action calculates the path, and, if one is found, succeeds and "feeds" it into the next action (say, "GoThere") through Component data.

And where Big Brain would be helpful here is to decide whether you continue to do "GoThere" (because the path is still accessible, for example, or because the destination hasn't been invalidated by some heuristic), or whether there's a _different_ action that you can take now that has higher priority (for example, you have a ProximityScorer that has detected that you're close enough to drink from a well, and so DrinkScorer shoots up in score, and ProximityScorer shoots down, and the Drink action fires.

Mapping that to your example, what I would expect is:

1. You have two scorer, "PatrolAreaScorer", and "FightEnemyScorer"
2. If there's no enemy present, "PatrolAreaScorer" wins, and you just fire an Action to wander around.
3. If there's at least one enemy within range, FightEnemyScorer spikes in value (which can scale based on how many enemies there are!), and it triggers a Steps action that looks like:

```
Steps(
  PickEnemy,
  ReadyWeapon,
  FireWeapon,
)
```

Where `PickEnemy` here is effectively your `FindPath`: you just run whatever algorithm you want based on the enemies in range to pick your target.

I think what you're getting at with your train of thought would entail having a dedicated Scorer for every single enemy, and use the Thinker system to calculate that. That's actually pretty doable but you'd need to write a custom Scorer that's responsible for spawning a unique Scorer for each of your entities' potential enemies. So that would be an M:N thing. Perfectly fine if you only have a few entities around, but if you're planning on spawning a big swarm, maybe not the best idea? I don't actually know how well big-brain would perform there.

Anyway, I have never tried this myself, but I bet you could just do this by grabbing the `Thinker` for your entity and shoving things into its `choices` field... if that field were public.

I think if you fork big-brain and try out this approach (by making that field available for you), and you find that it works for you, I'd be happy to take a PR with a reasonable PR, not for exposing the field directly, but an API to manipulate it.

How does that sound?

**Comment by rosofo** [comment]
First thanks for the detailed reply! This makes total sense, and I think I'll try using big-brain for its main use-case more first before experimenting as you say.

Something the docs might need is a clearer explanation of the lifecycle - how Scorers and Actions are spawned and the relationship with the `Builder` traits. Unless I've missed it. Maybe a flow diagram of some kind? Maybe the details are in the docs but are too spread out?

Anyway, I'll close this issue for now as I know how to proceed 👍
