### ISSUE TITLE
Evaluator with [0..1) range

### ISSUE THREAD

**Issue by agg23** [zkat/big-brain#36]
What is the intended use of the provided `Evaluator`s given the limited `Score` range of 0 to 1? Both exponential and sigmoid functions have very different utility in the domain of 0 to 1 vs the previous limit of 100. What is the intention behind clamping the `Score` values in the first place? I understand the desire to have the final output clamped for decision making, but I see no reason to clamp the intermediary values.

**Comment by zkat** [comment]
Originally, these were not clamped. After playing around with scorers and composition, though, I realized that a common problem that came up was that different Scorers would be hard to compose because they existed kind of in different score scales. And so the decision to be from 0 to 1 was to make all Scorers operate on "0% to 100%" as a scale, to make them easier to reason about during composition.
