### ISSUE TITLE
Make big-brain Game Engine independent

### ISSUE THREAD

**Issue by coder137** [zkat/big-brain#82]
Was looking at common utility AI systems like BehaviorTrees and GOAP which I could integrate into Godot 4 using the GDExtension interface (see https://github.com/godot-rust/gdext)

Would it be possible to make this AI system game engine independent (abstract away the Bevy-specific part) so that it can be used by other Game Engines?

Godot has these overrideable functions, (https://docs.godotengine.org/en/stable/tutorials/scripting/overridable_functions.html)

**Comment by zkat** [comment]
Unfortunately, the reason big-brain is tied to bevy is because it's very deeply integrated into bevy's ECS. At best, we could make our dependency on bevy more fine-grained so you only depend on bevy-ecs and a couple of other things, but once you take away the bevy aspects of big-brain... there's really not much left.

At best, I think big-brain can function as a reference for others to implement similar ECS-flavored Utility AI systems, since the core of them all is actually very small. And big-brain would definitely not be a very useful reference if you're trying to implement Utility AI in a non-ECS system (like Godot). For that, you might want to look at something like [Crystal AI](https://igiagkiozis.github.io/CrystalAI/), which was one of my main references when writing big-brain.
